export const GET_ALL_RESTAURANT="GET_ALL_RESTAURANT";
export const GET_ONE_RESTAURANT="GET_ONE_RESTAURANT";
export const ADD_FAV_RESTAURANT="ADD_FAV_RESTAURANT";
export const GET_FAVS_RESTAURANT="GET_FAVS_RESTAURANT";